version: '2'
services:
  atutor:
    image: 'danidemi/atutor:latest'
    stdin_open: true
    tty: true
    ports:
      - '80:80'
    volumes:
      - './website:/var/www/html'
  db:
    image: 'mysql:5.6'
    stdin_open: true
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=t00r
    volumes:
      - './mysql:/var/lib/mysql'
networks: {}
